name: 'er'

n_samples: 30

source_edge_prob: 0.3                   # Probability of connection between nodes in the source graph
target_edge_prob: 0.4                   # Probability of connection between nodes in the target graph

n_source_nodes: 160                     # Number of nodes in the source graph
n_target_nodes: 268                     # Number of nodes in the target graph

node_feat_init: 'adj'                   # Indicates how to initialize source node features. Options: 'adj', 'ones', 'random'
                                        # 'adj': initialize each node with the corresponding row of the adjacency matrix
                                        # 'ones': initialize each node with a vector of ones
                                        # 'random': initialize each node with a vector of random values

node_feat_dim: {n_source_nodes}        # Dimension of the source node features